### ISSUE TITLE
Python script for generating ROBIN

### ISSUE THREAD

**Issue by cibinjoseph** [Applied-Scientific-Research/robin-surface-mesh#5]
Hi, I created a Python script based on this code and have made it available [here](https://github.com/cibinjoseph/genROBIN). I've also added provisions to write out in other popular mesh file formats.

Just wanted to say thanks for the corrections you've incorporated and for making this available online!

**Comment by markstock** [comment]
Thank you, I'm glad you found it useful! I added a link to your code from the readme here. I think it will allow more people to use the geometry.

Could you add to your repository the gmsh script that converts to quads and higher-order elements?

**Comment by cibinjoseph** [comment]
Thanks!
I've incorporated your suggestions too!
